### ISSUE TITLE
Báo cáo tiến độ training ngày 25/11/2015

### ISSUE THREAD

**Issue by anhtuanqn1002** [anhtuanqn1002/Checklists#11]
# Hi anh,

Tình hình em mới học về .xib. Mỗi lần muốn sài .xib thì ta đăng ký bằng method registerregisterNib:forCellReuseIdentifier: . Lúc tạo cell, em có gọi hàm [tableView dequeueReusableCellWithIdentifier:@"CellWithXib"] và theo em thì lúc nào mình cũng dùng method này thay vì dùng [tableView dequeueReusableCellWithIdentifier:@"CellWithXib" forIndexPath:indexPath](sài cái này vào là nó lỗi với 1 cell thường, còn 1 cell xib thì không lỗi vì xib luôn tồn tại khi đăng kí). 
Trong lúc tạo 1 cell bình thường mà sài cái forIndexPath này nó không tạo cell mới cho em, mà nó crashed luôn anh. Nó không có tạo cho mình 1 cell mới nào hết anh.

**Comment by tungtx90** [comment]
`tableView dequeueReusableCellWithIdentifier:@"CellWithXib" forIndexPath:indexPath` method này sẽ dequeue cell và nếu nil sẽ tự động tạo 1 cell cho em. Nên kết quả hàm này không thể nil được. Em bị crash là do:
1. Cell Identifer em ghi sai.
2. Trong xib cell em chưa set Identifier cho nó.

**Comment by anhtuanqn1002** [comment]
Nếu em không dùng cell với .xib, cell cũng không kéo vào storyboard, nghĩa là identifier ban đầu sẽ không có(identifier này chỉ xuất hiện trong code), thì em dùng với forIndexPath nó sẽ trả về nil cho em, và không có tạo cell nào cho em cả, 
Còn như anh nói thì giờ em hiểu là nó giống như kết hợp với việc xét nếu dequeue mà ra nil thì nó tự tạo cell luôn (mình không phải xét để init cell) và yêu cầu là phải đúng identifier với xib hoặc là trong storyboard, còn với cell mới mình tự custom mà không dùng .xib thì mình vẫn phải kiểm tra nil đúng không anh.
