### ISSUE TITLE
Báo cáo tiến độ training ngày 05/11/2015

### ISSUE THREAD

**Issue by anhtuanqn1002** [anhtuanqn1002/Checklists#3]
Hi anh,
Theo các mục em phân hôm qua em định học thì trễ tiến độ.
Cụ thể các mục hôm qua em liệt kê là:
- The All lists screen
- Adding and editing checklists
- Putting to-do items into the checklists
- Doing saves differently
- Improving the data model
- Sử dụng Dictionary và NSUserDefaults
- The first-run experience
- Showing the number of to-do items remaining
- Sorting the lists

Tuy nhiên, hôm nay chỉ học được 2 mục đầu và gần hết mục thứ 3
Cụ thể:
- The all lists screen: học được biến kiểu static dùng sẽ tiết kiệm vùng nhớ hơn.  4 cách tạo 1 cell trong table view: tạo theo prototype cells, dùng static cell, sử dụng code và sử dụng nib. Sử dụng delegate.
- Adding/Editing: cách sử dụng mảng trong dữ liệu, chuyển view và sử dụng storyboardID.
- Putting to-do items into the checklists: phần này là cách đưa dữ liệu và sử dụng vòng lặp for để đưa dữ liệu vào checklists.

Ngày mai, làm nửa ngày. Dự tính sẽ học xong mục 3 và mục 4: Doing saves differently.

**Comment by tungtx90** [comment]
:+1: 
Phần 3 + 4 để 1/2 buổi sáng t7 làm. Mai em lo ôn bài đi
